# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07service\"\x1c\n\x0bUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"\x1e\n\x0cUserResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\"A\n\x17\x44\x65leteInterestsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rdeleted_count\x18\x02 \x01(\x05\x32M\n\x0bUserService\x12>\n\x0f\x43heckUserExists\x12\x14.service.UserRequest\x1a\x15.service.UserResponse2e\n\x14\x44\x61taCollectorService\x12M\n\x13\x44\x65leteUserInterests\x12\x14.service.UserRequest\x1a .service.DeleteInterestsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUEST']._serialized_start=26
  _globals['_USERREQUEST']._serialized_end=54
  _globals['_USERRESPONSE']._serialized_start=56
  _globals['_USERRESPONSE']._serialized_end=86
  _globals['_DELETEINTERESTSRESPONSE']._serialized_start=88
  _globals['_DELETEINTERESTSRESPONSE']._serialized_end=153
  _globals['_USERSERVICE']._serialized_start=155
  _globals['_USERSERVICE']._serialized_end=232
  _globals['_DATACOLLECTORSERVICE']._serialized_start=234
  _globals['_DATACOLLECTORSERVICE']._serialized_end=335
# @@protoc_insertion_point(module_scope)
